version: '3.9'
services:
  proxy:
    image: caddy:2.6-alpine
    container_name: reverse_proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  default:
    name: moukail
